create or replace PROCEDURE  P_INS_ENDERECO (
P_ENDERECO IN TBL_ENDERECO.ENDERECO%TYPE,
P_END_NUM IN TBL_ENDERECO.END_NUM%TYPE,
P_END_COMPL IN TBL_ENDERECO.END_COMPL%TYPE,
P_CEP IN TBL_ENDERECO.CEP%TYPE,
P_BAIRRO IN TBL_ENDERECO.BAIRRO%TYPE,
P_CIDADE IN TBL_ENDERECO.CIDADE%TYPE,
P_ESTADO IN TBL_ENDERECO.ESTADO%TYPE,
P_ID_USUARIO IN TBL_ENDERECO.ID_USUARIO%TYPE)

as

V_ENDERECO  TBL_ENDERECO%ROWTYPE;

BEGIN

    BEGIN

    V_ENDERECO.ID_ENDERECO := SQ_ENDERECO.NEXTVAL;
    V_ENDERECO.ENDERECO := P_ENDERECO;
    V_ENDERECO.END_NUM := P_END_NUM;
    V_ENDERECO.END_COMPL := P_END_COMPL;
    V_ENDERECO.CEP := P_CEP;
    V_ENDERECO.BAIRRO := P_BAIRRO;
    V_ENDERECO.CIDADE := P_CIDADE;
    V_ENDERECO.ESTADO := P_ESTADO;
    V_ENDERECO.FLG_ATIVO := 1;
    V_ENDERECO.ID_USUARIO := P_ID_USUARIO;

    INSERT INTO TBL_ENDERECO VALUES V_ENDERECO;

    COMMIT;

    EXCEPTION WHEN OTHERS THEN
        P_INS_LOG('ERRO AO TENTAR INSERIR NA TABELA TBL_ENDERECO - '||SQLCODE||' - '||SQLERRM);

    END;

END;