create or replace PROCEDURE  P_INS_LOG (P_MSG IN TBL_LOG.MSG%TYPE) 
as

V_MSG TBL_LOG.MSG%TYPE;

BEGIN

    V_MSG := P_MSG;

    BEGIN
        INSERT INTO TBL_LOG (ID_LOG,DATA_LOG,MSG) VALUES (
        SQ_LOG.NEXTVAL,
        SYSDATE,
        V_MSG);

        COMMIT;

    EXCEPTION WHEN OTHERS THEN
        INSERT INTO TBL_LOG (ID_LOG,DATA_LOG,MSG) VALUES (SQ_LOG.NEXTVAL,SYSDATE,'ERRO AO GRAVAR O LOG');
        COMMIT;
    END;

END;


