CREATE OR REPLACE VIEW VW_CADASTRO AS
SELECT 
    U.NOME,
    U.SEXO,
    E.ENDERECO,
    E.END_NUM,
    E.END_COMPL,
    E.CEP,
    E.BAIRRO,
    E.CIDADE,
    E.ESTADO,
    E.ID_ENDERECO,
    U.ID_USUARIO
FROM
    TBL_USUARIO U,
    TBL_ENDERECO E
WHERE
    U.ID_USUARIO = E.ID_USUARIO
AND U.FLG_ATIVO = 1
AND E.FLG_ATIVO = 1;
